### ISSUE TITLE
Docker in Docker guidance

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-eks-best-practices#210]
**Is your idea request related to a problem that you've solved? Please describe.**

docker:dind image might be needed for debugging on a EKS cluster. For example debugging an ECR issue.

Commonly it's used in CI processes https://docs.gitlab.com/ee/ci/docker/using_docker_build.html

**Describe the best practice**

It would be good if you could offer some guidance wrt **dind**, since it typically requires `privileged: true`

**Comment by jicowan** [comment]
@kaihendry thanks for the suggestion. I am hesitant to include this as a best practice since Dockershim is slated to be removed in 1.24. EKS will stop supporting Dockershim when it releases 1.24. Furthermore, EKS/Fargate and Bottlerocket are already using containerd. If you need to debug a container you will be able to use ephemeral containers starting in EKS 1.23. There are OSS projects like Kaniko and IMG and Buildah that allow you to build container images without having to run DnD. I rather recommend those than DnD which as you mentioned required privileged access.

**Comment by kaihendry** [comment]
Thank you! If I want a debug Docker pod with a working Docker daemon in 1.22, is that documented somewhere?

The below doesn't work. Error was something like **Cannot connect to the Docker daemon at unix:///var/run/docker.sock**

```
apiVersion: v1
kind: Pod
metadata:
  name: docker
spec:
  containers:
    - name: docker
      image: "docker:dind"
      command:
        - /bin/cat
      tty: true
      securityContext:
        privileged: true
```
