### ISSUE TITLE
ReadOnly role mapping best practice / guidance 

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-eks-best-practices#213]
Typically you need a read only account for audit purposes. 

The list from `kubectl get clusterroles` seem [poorly documented](https://aws.github.io/aws-eks-best-practices/security/docs/iam/). For example, what is the equivalent to https://github.com/glassechidna/trackiam/blob/master/policies/ReadOnlyAccess.json or are you expected to make your own?

I tried "view" but it failed whilst trying to view aws configmaps.

**Comment by jicowan** [comment]
You mean a read-only role in Kubernetes? There is a view role. You can see the permissions associated with that clusterrole by entering `kubectl get clusterroles view -o yaml` at a command prompt. It does include configmaps so I'm not sure why you weren't able to view them. You can also run `kubectl auth can-i get configmaps` to see whether your user has rights to view configmaps.

**Comment by jimmyraywv** [comment]
@kaihendry The k8s `view` Cluster Role does permit access to `get`, `list`, and `watch` Config Maps, as seen below.

**view Cluster Role**
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: view
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - persistentvolumeclaims
  - persistentvolumeclaims/status
  - pods
  - replicationcontrollers
  - replicationcontrollers/scale
  - serviceaccounts
  - services
  - services/status
  verbs:
  - get
  - list
  - watch … (edited for brevity)
```

Then you could create a Cluster Role Binding or Role Binding to a group entry in the `kube-system:aws-auth` Config Map group entry, that references a role, like below.

**Cluster Role Binding**
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-readonly
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: readonly-users
```

**aws-auth entry**
```
apiVersion: v1
data:
  mapRoles: |
...
    - groups:
      - readonly-users
      rolearn: arn:aws:iam::123456789012:role/ReadOnly
```
