### ISSUE TITLE
Proposal: add a Sigstore k8s registry deprecation policy

### ISSUE THREAD

**Issue by hectorj2f** [aws/aws-eks-best-practices#300]
**Is your idea request related to a problem that you've solved? Please describe.**

Within Sigstore community, we were wondering if you'd be interested on adding a third alternative to the current [k8s-registry-deprecation](https://github.com/aws/aws-eks-best-practices/commits/master/policies/k8s-registry-deprecation) examples.  
In our project [sigstore/policy-controller](https://docs.sigstore.dev/policy-controller/overview/), we've defined a rich API to enforce image policies on a cluster on verifiable supply-chain metadata from cosign. 

Let's us know what you think about it. We'd be happy to open a PR adding support for a Sigstore policy to handle a similar behauvior.

```yaml
...
spec:
  mode: warn
  images:
  - glob: "k8s.gcr.io/**"
  authorities:
  - name: k8s-deprecated
    static:
      action: pass
  policy:
    type: rego
    data: |
      package sigstore
      isCompliant[response] {
        response := {
          "result" : true,
          "error" : "",
          "warning" : "This repo has been deprecated: https://kubernetes.io/blog/2023/02/06/k8s-gcr-io-freeze-announcement/"
        }
      }
```
