### ISSUE TITLE
Network Policy can be used to selectively allow metadata access to the pods

### ISSUE THREAD

**Issue by sotoiwa** [aws/aws-eks-best-practices#84]
**Is your idea request related to a problem that you've solved? Please describe.**

- [Restrict access to the instance profile assigned to the worker node](https://aws.github.io/aws-eks-best-practices/security/docs/iam/#restrict-access-to-the-instance-profile-assigned-to-the-worker-node)
- [When your application needs access to IDMS, use IMDSv2 and increase the hop limit on EC2 instances to 2](https://aws.github.io/aws-eks-best-practices/security/docs/iam/#when-your-application-needs-access-to-idms-use-imdsv2-and-increase-the-hop-limit-on-ec2-instances-to-2)
- [Alternative approaches](https://aws.github.io/aws-eks-best-practices/security/docs/iam/#alternative-approaches)

The above topics describes how to block access to instance metadata

In my experience, the Kinesis Client Library used by some Pods [does not support IRSA](https://github.com/awslabs/amazon-kinesis-client-nodejs/issues/79). So I could not block metadata access because using only IMDSv2 and setting hop count to 1 or using iptables would target all the Pods on the node.

However I could use Kubernetes Network Policy to selectively allow metadata access to the pods.

How about adding a description of how to block metadata access using Network Policy?

**Describe the best practice**

You can use Kubernetes Network Policy to block metadata access and selectively allow to some pods.

At first, block access to the metadata service from all pods by adding following policy.

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-metadata-access
  namespace: example
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 169.254.169.254/32
```

Then allow access from some pods by adding following policy.

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-metadata-access
  namespace: example
spec:
  podSelector:
    matchLabels:
      app: myapp  
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 169.254.169.254/32
```
